### ISSUE TITLE
tcl_platform(pathSeparator)

### ISSUE THREAD

**Issue by aplsimple** [arjenmarkus/cip-git#1]
In cip.tcl, lines 259..263, it's better to use `$::tcl_platform(pathSeparator)`
Thanks.

**Comment by arjenmarkus** [comment]
You're absolutely right! Thanks for this correction. I had all but forgotten about that part of tcl_platform.

**Comment by arjenmarkus** [comment]
I will check in the correction when i have tested it locally.

**Comment by arjenmarkus** [comment]
Done. It made me realise that the example directory was not entirely complete :).
